import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./Header";
import Head from "next/head";
import { Box, List, ListItem, ListItemText, useTheme } from "@mui/material";
import Image from "next/image";
import LeftVerticalNavbar from "@/components/LeftVerticalNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>FastGpt</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <LeftVerticalNavbar /> */}
      <main dir="rtl">{children}</main>
    </>
  );
}
