import type { Metadata } from "next";
import { Header } from "./Header";
import Head from "next/head";
import { Footer } from "./Footer";
import { LeftVerticalNavbar } from "@/components/LeftVerticalNavbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>FastGpt</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main dir="rtl">
        <Toaster position="top-right" reverseOrder={false} />
        {children}
      </main>
      <Footer />
    </>
  );
}
